version: '3.8'

services:
  web-production:
    build:
      context: .
      target: runner
    ports:
      - "3003:3003"
    restart: unless-stopped
    volumes:
      - /home/tgh2171/www/html/do-cu-vui-hung-net/logs:/var/log/nginx
